#!/usr/bin/env sh

branch=$(git symbolic-ref --short HEAD)

case "$branch" in
  master|develop|staging|production|release/*)
    echo "Cannot commit to remote $branch branch, please create your own branch and use PR."
    exit 1
    ;;
esac

pnpm lint-staged